Kagetsu/config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  get 'rules/index'
  get 'profile/index'

  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"


  resources :users do
    resources :comments, only: [:new, :create, :index]
    resources :profile, only: [:edit, :update]
    resources :comments, only: [:new, :create]
    
	resources :characters, except: [:index]
	resources :friends
	post 'set_default_character'
	get 'preview'
  end


  resources :comments


  controller :users do
    get 'signup' => :new
    post 'signup' => :create
  end

  controller :sessions do
	get 'login' => :new
    post 'login' => :create
	get 'logout' => :destroy
  end

  root to: 'comments#new'

end

Kagetsu/app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :characters
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :comments, dependent: :delete_all
  has_many :rooms,dependent: :destroy
  attr_accessor :password
  attr_accessor :profile_id

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..30 }
  validates :password, :confirmation => true #password_confirmation attribute
  validates_length_of :password, :in => 3..30, :on => :create

  before_save :encrypt_password
  before_save :create_profile
  after_save :clear_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def clear_password
	self.password_hash = nil
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def create_profile
	adjs = ["autumn", "hidden", "bitter", "misty", "silent", "empty", "dry", "dark"]
	nouns = ["waterfall", "river", "breeze", "moon", "rain", "wind", "sea", "morning"]
    self.profile = Profile.create(:nickname => [adjs.sample, nouns.sample].join('_'), :gender => 0)
  end



  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject{ |user| user.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?
    param.downcase!
    (username_matches(param)).uniq 
  end

  def self.username_matches(param)
    matches('username', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
end

Kagetsu/app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout "userform", except: [:index, :show]

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash.now[:alert] = "There was a problem creating your account."
			render "new"
		end
	end

	def set_default_character
		@user = User.find(current_user)
		@user.profile.update_attribute(:character_id, params[:character_id])
		@character = current_character
		respond_to do |format|
			format.js
		end
	end

	def preview
		@user = User.find(params[:user_id])
		respond_to do |format|
			format.html
			format.js
		end
	end

private
	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation, :profile_id)
	end
end

Kagetsu/app/helpers/users_helper.rb
module UsersHelper
end

Kagetsu/app/views/users/my_friends.html.erb
<div class="module-header">
	<div class="module-title"><h1>My Friends (<%= @friends.size %>)</h1></div>
</div>

<div class="wrapper">
	<% if @friends.size > 0 %>
		<% @friends.each do |user| %>
			<%= render 'userbox', { user: user, mode: 'f'} %>
		<% end %>
	<% end %>
	<%= link_to '', new_user_friend_path(@user), { 
		:class=>"add-button", 
		:title=>"Add New Friends" } %>
</div>
<%= render 'friends/lookup' %> 


<% if @friendships.size > 0 %>
	<table class ="table table-striped">
		<thead>
			<tr>
				<th colspan = "2" class="page-header">
					<h2>My Friends</h2>
				</th>
			</tr>

			<tr>
				<th>Username</th>
				<th>Characters</th>
			</tr>
		</thead>

		<tbody>
		  	<% @friendships.each do |friend| %>
		    <tr>
		    	<td><%= friend.username %></td>
			    <td><%= friend.characters %></td>
			      
			    <td>
			    	<%= link_to 'View Profile', user_path(friend), class:"btn btn-primary btn-xs" %>
			    	
			     
			      	<%= link_to 'Remove Friend', friendship_path(friend),
			              :method=> :delete,
			              :data=> { :confirm=> 'Are you sure?' },
			              :class => "btn btn-xs btn-danger" %>
			    </td>
		    </tr>
		  	<% end %>
		 </tbody>
	 </table>

<% else %>
	<div class = 'row col-lg-12'>
		<p class = "lead">You don't have any friends yet. Please add some!</p>
	</div>
<% end %>

Kagetsu/app/views/users/new.html.erb
<div class="module-header">
	<div class="left-control"><%= link_to 'Cancel', :root, :class=>"btn btn-xs btn-default" %></div>
	<div class="module-title">Sign Up</div>
</div>

<div class="main-login panel panel-default">
	<div class="panel-body">
		<% if flash.any? %>
			<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only"></span>
				<% flash.each do |key, value| %>
					<%= value %>
				<% end %>
			</div>
		<% end %>

		<%= form_for @user do |f| %>
			<div class="form-group">
				<%=f.label :username, nil, class: 'control-label' %>
				<%=f.text_field :username, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%=f.label :password, nil, class: 'control-label' %>
				<%=f.password_field :password, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%=f.label :password_confirmation, nil, class: 'control-label' %>
				<%=f.password_field :password_confirmation, class: 'form-control' %>
			</div>

			<%= f.submit "Sign Up", class: "btn btn-lg btn-primary btn-block" %>
		
			<div class="userauth-extra">
				Already have an account?
				<%= link_to 'Login', login_path %>
			</div>
		<%end%>
	</div>
</div>

Kagetsu/app/views/users/preview.js.erb
$("#my-modal-title").html("User Profile and Characters");
$("#my-modal-body").html("<%= escape_javascript(render 'profile/detail', { user: @user }) %>");

Kagetsu/app/views/users/set_default_character.js.erb
$("#user_profile_image img").each(function() {
	if(this.id == "userprofile_" + <%= params[:character_id] %>)	{ 
		$(this).show();
	}
	else {
		$(this).hide();
	}
});

Kagetsu/app/views/users/show.html.erb
<div class="module-header">
	<% if current_user != @user %>
	<div class="left-control"><%= link_to 'Back', user_friends_path(current_user), :class=>"btn btn-xs btn-default" %></div>
	<% end %>
	<div class="module-title"><h1>User Profile and Characters</h1></div>
</div>

<div class="wrapper">
	<div class="detail-box">
		<% if current_user == @user %>
		<div class="controls">
			<%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> Edit Profile'),
				edit_user_profile_path(current_user, current_user.profile),
				:class => "btn btn-default",
				:title => "Edit Profile" %>
		</div>
		<% end %>
		<div class="profile-image">
			<% if @user.profile && @user.profile.image? %>
				<%= image_tag @user.profile.image.url %>
			<% else %>
				<%= image_tag "default_profile.jpg" %>
			<% end %>
		</div>
		<div class="details">
			<% if current_user == @user %>
			<div class="row">
				<div class="col-md-2"><strong>Username</strong>: </div>
				<div class="col-md-10"><%= @user.username %></div>
			</div>
			<% end %>
	
			<div class="row">
				<div class="col-md-2"><strong>Nickname</strong>: </div>
				<div class="col-md-10"><%= @user.profile.nickname %></div>
			</div>

			<% if current_user == @user || @user.profile.is_gender_public %>				
			<div class="row">
				<div class="col-md-2"><strong>Gender</strong>: </div>
				<div class="col-md-10">			
				<% if @user.profile.gender == 1 %> Male
				<% elsif @user.profile.gender == 2 %> Female
				<% else %> <span class="faded">Not set</span><% end %>
				</div>
			</div>
			<% end %>

			<% if current_user == @user || @user.profile.is_dob_public %>				
			<div class="row">
				<div class="col-md-2"><strong>Date of Birth</strong>: </div>
				<div class="col-md-10">
					<% if @user.profile.dob %>
						<%= @user.profile.dob %>
					<% else %>
						<span class="faded">Not set</span>
					<% end %>
				</div>
			</div>
			<% end %>
	
			<hr />
			<div class="item">
				<strong>Comment</strong><br />
				<% if @user.profile.comment.present? %>
					<%= simple_format(@user.profile.comment) %>
				<% else %>
					<div class="empty">There is no comment</div>
				<% end %>
			</div>
		</div>
	</div>
	<hr />
	<h2>Characters (<%= @user.characters.length %>/<%= max_num_characters %>)</h2>
	<%= render 'characters/list' %>
</div>