Kagetsu/config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  get 'rules/index'
  get 'profile/index'

  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"


  resources :users do
    resources :comments, only: [:new, :create, :index]
    resources :profile, only: [:edit, :update]
    resources :comments, only: [:new, :create]
    
	resources :characters, except: [:index]
	resources :friends
	post 'set_default_character'
	get 'preview'
  end


  resources :comments


  controller :users do
    get 'signup' => :new
    post 'signup' => :create
  end

  controller :sessions do
	get 'login' => :new
    post 'login' => :create
	get 'logout' => :destroy
  end

  root to: 'comments#new'

end

Kagetsu/app/models/room.rb
class Room < ActiveRecord::Base
  has_many :comments, dependent: :delete_all
  belongs_to :user
end

Kagetsu/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def show
    @room = Room.includes(:comments).find_by(id: params[:id])
    @comments = Comment.new

  end

  def create
    @rooms = Room.all
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = 'Chat room added!'
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  private

  def room_params
    params.require(:room).permit(:title, :description)
  end
end

Kagetsu/app/helpers/rooms_helper.rb
module RoomsHelper
end

Kagetsu/app/views/rooms/_room.html.erb
<li><%= link_to "Enter #{room.title}", room_path(room) %></li>

Kagetsu/app/views/rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @rooms %>
</ul>

Kagetsu/app/views/rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true, class: 'form-control' %>
    
  </div>
  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

Kagetsu/app/views/rooms/show.html.erb
<h1><%= @room.title %></h1>

<div id="comment">
  <%= render @room.comments %>
</div>