Kagetsu/config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  get 'rules/index'
  get 'profile/index'

  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"


  resources :users do
    resources :comments, only: [:new, :create, :index]
    resources :profile, only: [:edit, :update]
    resources :comments, only: [:new, :create]
    
	resources :characters, except: [:index]
	resources :friends
	post 'set_default_character'
	get 'preview'
  end


  resources :comments


  controller :users do
    get 'signup' => :new
    post 'signup' => :create
  end

  controller :sessions do
	get 'login' => :new
    post 'login' => :create
	get 'logout' => :destroy
  end

  root to: 'comments#new'

end

Kagetsu/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action do
		authorize(user)
	end

	def index
		@user = user
		@friends = user.friends.joins(:profile).where("profiles.nickname LIKE ?", "%#{params[:search_param]}%")
		@friends = current_user.except_current_user(@friends)
	end

	def new
		@user = user
		@friends = User.joins(:profile).where("profiles.nickname LIKE ?", "%#{params[:search_param]}%")
		@friends = current_user.except_current_user(@friends)
	end

	def create
		@user = user
		@friend = user.friendships.new(friend_id: params[:friend])
		if @friend.save
			redirect_to :back
		else
			redirect_to :back, flash[:error] = "There was an error with adding the user as a friend."
		end
	end

	def destroy
		@user = user
		@friend = user.friendships.where(friend_id: params[:id]).first 
		@friend.destroy
		redirect_to user_friends_path(user)
	end

private
	def user
		User.find(params[:user_id])
	end

	def friend_params
	params.require(:friend).permit(:user_id, :friend_id)
	end
end

Kagetsu/app/helpers/friends_helper.rb
module FriendsHelper
end

Kagetsu/app/views/friends/_lookup.html.erb
<div id="friend-lookup">
	<h3>Search for Friends</h3>
	<%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
	<div class ="form-group row no-padding text-center col-md-12">
		<div class="col-md-10">
			<%= text_field_tag :search_param, params[:search_param], 
				placeholder: 'username', autofocus: true, 
				class: 'form-control search-box input-lg' %>
		</div>
		<div class="col-md-2">
			<%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
				<i class="fa fa-search"></i> Look up a friend
			<% end %>
		</div>
	</div>
	<% end %>
	
	<%= render 'common/spinner' %>
	<% if @users %>
		<% if @users.size > 0 %>
			<h3> Search Results</h3>
			<div id="friend-lookup-results" class="well results-block col-md-10">
				<table class="search-results-table col-md-12">
					<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><strong>Username: </strong> <%= user.username %> </td>
						<td><strong>Profile: </strong> <%= link_to "View Profile", user_path(user), 
							class: "btn btn-xs btn-success" %>
							<% if current_user.not_friends_with?(user.id) %>
								<%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user), 
								class: "btn btn-xs btn-success", method: :post %>
							<% else %>
								<span class="label label-primary">
									You are friends
								</span>
							<% end %>
						</td>
					</tr>
					<% end %>	
					</tbody>
				</table>
			</div>
		<% else %>
			<p class="lead col-md-12">
				No people match this search criteria
			</p>
		<% end %>
	<% end %>

	<div id="friend-lookup-errors"></div>
</div>

Kagetsu/app/views/friends/_userbox.html.erb
<div class="user-box">
	<% if mode == 's' %>
		<% if current_user.not_friends_with?(user.id) %>
			<span class="label">Stranger</span>
		<% else %>
			<span class="label label-primary">Friend</span>
		<% end %>
	<% end %>

	<div class="profile-image">
		<% if user.profile && user.profile.image? %>
			<%= image_tag user.profile.image.url %>
		<% else %>
			<%= image_tag "default_profile.jpg" %>
		<% end %>
	</div>

	<div class="main-data"><%= user.profile.nickname %></div>
	
	<div class="sub-data">
		<% if user.profile.is_gender_public && user.profile.gender > 0 %>
			<% if user.profile.gender == 1 %> Male
			<% elsif user.profile.gender == 2 %> Female
			<% else %> Unknown <% end %>
		<% end %>
		<% if user.profile.is_dob_public && user.profile.dob %>				
			(<%= user.profile.dob %>)
		<% end %>
		&nbsp;
	</div>
	
	<div class="controls">
		<div class="btn-group btn-group-justified">
		<% if mode == 'f' %>
			<%= link_to raw('<span class="glyphicon glyphicon-trash"></span> Remove'),
				user_friend_path(@user, user),
				:method=> :delete,
				:data=> { :confirm=> 'Are you sure?' },
				:class => "btn btn-sm btn-danger" %>
			<%= link_to raw('<span class="glyphicon glyphicon-new-window"></span> Details'),
				user_preview_path(user), 
				:class => "btn btn-sm btn-default",
				:remote => true,
				:title => "Show Details", 
				data: {toggle: "modal", target: "#my-modal"} %>
			<%= link_to raw('<span class="glyphicon glyphicon-comment"></span> Chat'),
				new_comment_path,
				:class => "btn btn-sm btn-default",
				:title => "Show Details" %>
		<% else %>
			<% if current_user.not_friends_with?(user.id) %>
				<%= link_to raw('<span class="glyphicon glyphicon-plus"></span> Add'), 
					user_friends_path(current_user, friend: user), 
					:class => "btn btn-sm btn-success",
					:title => "Add to My Friends",
					:method => :post %>
			<% end %>
			<%= link_to raw('<span class="glyphicon glyphicon-new-window"></span> Details'),
				user_preview_path(user), 
				:class => "btn btn-sm btn-default",
				:remote => true,
				:title => "Show Details", 
				data: {toggle: "modal", target: "#my-modal"} %>
		<% end %>
		</div>
	</div>
</div>

Kagetsu/app/views/friends/index.html.erb
<div class="module-header">
	<div class="module-title"><h1>My Friends (<%= @friends.size %>)</h1></div>
</div>

<div class="wrapper">
	<% if @friends.size > 0 %>
		<% @friends.each do |user| %>
			<%= render 'userbox', { user: user, mode: 'f'} %>
		<% end %>
	<% end %>
	<%= link_to '', new_user_friend_path(@user), { 
		:class=>"add-button", 
		:title=>"Add New Friends" } %>
</div>

Kagetsu/app/views/friends/new.html.erb
<div class="module-header">
	<div class="left-control"><%= link_to 'Back', user_friends_path(@user), :class=>"btn btn-xs btn-default" %></div>
	<div class="module-title"><h1>Search</h1></div>
</div>

<div class="wrapper" id="friend-lookup">
	<%= form_tag new_user_friend_path(@user), method: :get, id: 'friend-lookup-form' do %>
	<div class ="form-group">
		<div class="input-group">
			<%= text_field_tag :search_param, params[:search_param], 
				placeholder: 'nickname', autofocus: true, 
				class: 'form-control search-box input-lg' %>
			<span class="input-group-btn">
				<%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
					<span class="glyphicon glyphicon-search"></span> Search
				<% end %>
			</span>
		</div>
	</div>
	<% end %>
	<hr />
	<%= render 'common/spinner' %>
	<% if @friends && @friends.size > 0 %>
		<div id="friend-lookup-results">
			<% @friends.each do |user| %>
			<%= render 'userbox', { user: user, mode: 's' } %>
			<% end %>
		</div>
	<% else %>
		<div class="empty">
			No users match the search criteria
		</div>
	<% end %>
	<div id="friend-lookup-errors"></div>
</div>